title: Test Github Page
author: raydala
email: muetzenschaf@outlook.de
description: > # this means to ignore newlines until "baseurl:"
Testing der Github Pages-Funktion von Github.
theme: minima
# social links
twitter_username: muetzenschaf # DO NOT include the @ character, or else the build will fail!
github_username:  raydala # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
